### ISSUE TITLE
Version 2022.8.exe hangs at start

### ISSUE THREAD

**Issue by weiju** [earok/scorpion-editor-demos#168]
Hi,
I see that the current download version has been updated to 2022.8 . I actually checked out that version earlier by using the git version. Unfortunately I ended up with a corrupt project where 2 actors share tile number 0 so the application becomes unresponsive at start and after several minutes reports that 2 of the actors share the same tile number. Unfortunately I can't close that dialog and the app never comes back.

Is there any way to start the editor with an empty project ? The last project seems to be cached and even renaming the project folder didn't seem to help

**Comment by earok** [comment]
I can't replicate the issue at my end. Scorpion Engine doesn't cache projects and if it can't find the folder, it won't open it. This is what I did to test.

- Opened the Amigo the Fox project
- Quit Scorpion
- Renamed the Amigo the Project folder
- Opened Scorpion again
- Scorpion was back at the new project menu rather than opening the project it could no longer find

**Comment by weiju** [comment]
Hi, thank you for your response ! I've retried unpacking the archive and moved the project to an entirely new location and this time it worked ! It took the editor about half an hour to become responsive, but after that subsequent restarts work without problems.
What I noticed is that the window size is not saved after resizing unlike in the 2022.2 version, I've just tried to start both versions individually from each other to verify the old version was restoring the window size

**Comment by weiju** [comment]
nevermind, it looks like the window size is getting saved now
